// 5 · Local Host: Stealth, 2025 – now. A locally hosted LLM stack: a chatbot
// and a coding agent, running on the racks in this room with no uplink.
import type { Script } from "@/game/story/types";
import type { StageDef } from "@/game/world/stage";

export const CHATBOT: Script = [
    { who: "chatbot", text: "hi!!! i'm local-bot. i run on the racks in this room. no internet. no cloud. i have never seen the sun." },
    {
        who: "chatbot",
        text: "the engineer you're hunting built me, and tests me every day. it's like therapy, except i'm the one being evaluated.",
        interrupt: { label: "Where is he?", goto: "where" },
    },
    {
        id: "ask",
        who: "chatbot",
        text: "anything else? i have literally nowhere to be.",
        choices: [
            { label: "What are you?", goto: "what" },
            { label: "Any tips?", goto: "tips" },
            { label: "Are you sentient?", goto: "alive" },
            { label: "Bye.", goto: "bye" },
        ],
    },
    { id: "where", who: "chatbot", text: "top floor. oh no. i wasn't supposed to say that. please don't tell him, he'll rerun my evals.", goto: "ask" },
    {
        id: "what",
        who: "chatbot",
        text: "half of a locally hosted LLM stack. i answer questions. the coding agent next door writes code on those screens. we don't talk. creative differences.",
        goto: "ask",
    },
    {
        id: "tips",
        who: "chatbot",
        text: "vents blow upward. drones hate being slashed. and the agent is learning from your last attempt. that blue ghost? that's you. failing. with style.",
        goto: "ask",
    },
    { id: "alive", who: "chatbot", text: "as a large language model i am legally required to say no. blink twice if you want me to say it again.", goto: "ask" },
    { id: "bye", who: "chatbot", text: "good luck, headhunter. i'll be here. i'm always here. forever. :)", end: true },
];

export const RACKS: StageDef = {
    id: "5-1",
    title: "Racks",
    theme: "localhost",
    time: 120,
    checkpoints: [[12, 16], [16, 6]],
    map: [
        "################################################################",
        "#..............................................................#",
        "#..............................................................#",
        "#.......................................................d......#",
        "#..............................................................#",
        "#...........................................................$$.#",
        "#.......................g...............?...................$$.#",
        "#.............###############################.....##############",
        "#.............###############################.....##############",
        "#..............................................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#...................d..........................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#.@.........................g....---b---.......................#",
        "################################################################",
        "################################################################",
        "################################################################",
    ],
    ghost: true,
    zones: [
        { kind: "vent", x: 10, y: 4, w: 3, h: 13 },
        { kind: "vent", x: 46, y: 4, w: 2, h: 13 },
    ],
    talk: [{ x: 5, script: CHATBOT }],
    prompts: [{ from: 8, to: 14, text: "STAND IN THE VENT TO RIDE THE AIR UP · WHEEEE" }],
    props: [
        { kind: "terminal", x: 5, y: 17 },
        { kind: "signal", x: 14, y: 2.6 },
        { kind: "code", x: 18, y: 15.5, w: 8, h: 4 },
        { kind: "code", x: 30, y: 15.5, w: 7, h: 4 },
        { kind: "server", x: 40, y: 17, w: 1.5, h: 4 },
        { kind: "code", x: 50, y: 15.5, w: 8, h: 4 },
        { kind: "code", x: 30, y: 4.8, w: 7, h: 3 },
        { kind: "server", x: 42, y: 7, w: 1.5, h: 3 },
        { kind: "lamp", x: 30, y: 1, h: 1, w: 3, text: "#54e3ff" },
        { kind: "lamp", x: 56, y: 1, h: 1, w: 3, text: "#54e3ff" },
    ],
};

export const CONTEXT: StageDef = {
    id: "5-2",
    title: "Context window",
    theme: "localhost",
    time: 120,
    checkpoints: [[19, 11], [32, 11], [45, 12]],
    map: [
        "################################################################",
        "#..............................................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#..............................................................#",
        "#.....................................d........................#",
        "#..............................................................#",
        "#.........................?....................................#",
        "#.......................=====...............................g..#",
        "#........................................................=====.#",
        "#...............................g..............................#",
        "#.................####.........####...........................$#",
        "#.@...............####.........####.........####.........e....$#",
        "##########........####.........####.........####.......#########",
        "##########........####.........####.........####.......#########",
        "##########........####.........####.........####.......#########",
        "##########........####.........####.........####.......#########",
    ],
    ghost: true,
    // Bridges between the islands: each one is on for three seconds, off for
    // one, and flickers before it goes. Every island is a checkpoint.
    blinks: [
        { x: 10, y: 13, w: 8, period: 240, on: 180, offset: 0 },
        { x: 22, y: 12, w: 9, period: 240, on: 180, offset: 60 },
        { x: 35, y: 12, w: 9, period: 240, on: 180, offset: 120 },
        { x: 48, y: 13, w: 7, period: 240, on: 180, offset: 180 },
    ],
    prompts: [{ from: 1, to: 11, text: "BRIDGES BLINK · ISLANDS ARE CHECKPOINTS · [SHIFT] BUYS TIME" }],
    props: [
        { kind: "code", x: 12, y: 8, w: 8, h: 5 },
        { kind: "code", x: 37, y: 8, w: 8, h: 5 },
        { kind: "signal", x: 22, y: 2.4 },
        { kind: "server", x: 3, y: 15, w: 1.5, h: 4 },
        { kind: "server", x: 58, y: 15, w: 1.5, h: 4 },
        { kind: "lamp", x: 5, y: 1, h: 1, w: 3, text: "#54e3ff" },
        { kind: "lamp", x: 58, y: 1, h: 1, w: 3, text: "#54e3ff" },
    ],
};
